# LAYER 1: CORE INFRASTRUCTURE
from MODULES.LAYER_1_CORE_INFRASTRUCTURE.config import (
    db,
    oauth,
    IS_PRODUCTION,
    SECRET_KEY,
    ADMIN_EMAIL,
    ADMIN_PASSWORD,
    SQLALCHEMY_DATABASE_URI,
    SQLALCHEMY_TRACK_MODIFICATIONS,
    SQLALCHEMY_ENGINE_OPTIONS,
    UPLOAD_FOLDER,
    MAX_CONTENT_LENGTH,
    APP_BASE_URL,
    FEEDBACK_TO_EMAIL,
    ALLOWED_EXTENSIONS,
    ALLOWED_RESUME_EXTENSIONS,
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    has_google_oauth,
    GEMINI_API_KEY,
    MODEL_NAME
)
